# Generated by Django 5.2.6 on 2025-09-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=255)),
                ('pic', models.FileField(max_length=155, upload_to='student')),
                ('regdate', models.DateField(auto_now=True, max_length=30)),
            ],
        ),
    ]
