# Generated by Django 5.2.6 on 2025-10-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_admin_delete_adlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
