# Generated by Django 5.2.6 on 2025-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_branchs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Branchs',
        ),
    ]
