# Generated by Django 5.2.6 on 2025-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_branch_delete_branchs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='Branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
