# Generated by Django 5.2.6 on 2025-09-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('file', models.FileField(max_length=255, upload_to='study')),
            ],
        ),
    ]
