# Generated by Django 5.2.6 on 2025-09-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
